### ISSUE TITLE
最新自动编译版本bug

### ISSUE THREAD

**Issue by forchannot** [Coolapk-UWP/Coolapk-Lite#18]
`登录后点击收藏或者浏览历史就会卡死，无法加载也无法点击其他东西，不知道生成的日志是否有帮助`
2|2022-07-28T19:27:42.4860527+00:00|ERROR|2|Exception|
Message: Excep_FromHResult 0x802B0014
-2144665580(0x802b0014) --> System.Exception: Excep_FromHResult 0x802B0014
2|2022-07-28T19:28:06.8576596+00:00|ERROR|2|Exception|
Message: Excep_FromHResult 0x802B0014
-2144665580(0x802b0014) --> System.Exception: Excep_FromHResult 0x802B0014
2|2022-07-28T19:28:23.5148120+00:00|ERROR|2|Exception|
Message: Excep_FromHResult 0x802B0014
-2144665580(0x802b0014) --> System.Exception: Excep_FromHResult 0x802B0014
2|2022-07-28T19:28:43.2317205+00:00|ERROR|2|Exception|
Message: Excep_FromHResult 0x802B0014
-2144665580(0x802b0014) --> System.Exception: Excep_FromHResult 0x802B0014

**Comment by wherewhere** [comment]
不能，这些代码一点用也没有。。。

**Comment by wherewhere** [comment]
可能解决了这个问题
