### ISSUE TITLE
无法链接服务器

### ISSUE THREAD

**Issue by cool-delete** [Coolapk-UWP/Coolapk-Lite#37]
### Describe the bug

一片空白

### Steps to reproduce the bug

1.打开应用
2.点击用户

### Screenshots

![image](https://user-images.githubusercontent.com/13638610/230761585-ad9d072a-315c-48c4-b939-8362a5f4ac4e.png)

### App version

0.0.1

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### Device

Desktop

### Additional context

[Uploading Log - 20230409.log…]()

**Comment by wherewhere** [comment]
你Log没有传上来
