### ISSUE TITLE
希望未登入下時，左邊選單可以收藏話題，以達到快速開啟該主題

### ISSUE THREAD

**Issue by skysumbra** [Coolapk-UWP/Coolapk-Lite#40]
### Describe your feature request

希望未登入下時，左邊選單可以收藏話題，以達到快速開啟該主題

### How important is this to you?

Nice-to-have

### Describe the solution you'd like

左邊畫面有選單可以直接收藏話題

**Comment by wherewhere** [comment]
真巧啊，刚刚加入了书签，你可以手动添加收藏夹了

**Comment by wherewhere** [comment]
点分享，获取链接，然后到收藏夹加入收藏

**Comment by skysumbra** [comment]
在右邊內容點了分享，然後複製連結嗎?
到收藏夾後的畫面如下，沒有其他的按鈕可以點了
![圖片](https://user-images.githubusercontent.com/24444616/235336693-3dd36762-c936-41ed-96d8-6b05addf17e5.jpg)

**Comment by wherewhere** [comment]
请使用每日编译版

**Comment by skysumbra** [comment]
請問是如何下載?
首頁的下方說明，連結是realease
