### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by bluebluff** [Coolapk-UWP/Coolapk-Lite#46]
### Describe the bug

输入账号和密码后，选择同意，点击登录后，啥反应都没有。

### Steps to reproduce the bug

2023-08-22T21:54:37.6752131+00:00|ERROR|8|NetworkHelper|
Message: net_http_message_not_success_statuscode. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485
HResult: -2146233088 (0x80131500)
   at CoolapkLite!<BaseAddress>+0xb00438
   at CoolapkLite!<BaseAddress>+0xa2e3b7
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xaf6b18
 --> System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485
   at CoolapkLite!<BaseAddress>+0xb00438
   at CoolapkLite!<BaseAddress>+0xa2e3b7
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7

### App version

0.0.2

### Windows version

Windows 10 version 2004 (19041, May 2020 Update)

### Device

Desktop

**Comment by wherewhere** [comment]
登陆不上一般是酷安炸了或者被封了，无法解决

**Comment by bluebluff** [comment]
可我的手机端可以正常登录啊。是不是因为我的ip地址在国外？但我手机端依然是正常可以反复登录的

**Comment by wherewhere** [comment]
我也是能正常登陆的，那么就是你的电脑出问题了<img alt="流汗滑稽" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png" width="20px" /><img alt="流汗滑稽" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png" width="20px" /><img alt="流汗滑稽" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />
