### ISSUE TITLE
一直卡在这个界面

### ISSUE THREAD

**Issue by ZhouJze** [Coolapk-UWP/Coolapk-Lite#47]
### Describe the bug

![联想截图_20230904151828](https://github.com/Coolapk-UWP/Coolapk-Lite/assets/116236596/ca8b9d4b-26ec-4120-89e3-a403d29ff300)
一直是这个界面，然后一段时间后闪退 

### Steps to reproduce the bug

安装-打开

### App version

0.0.2

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### Device

Desktop

**Comment by wherewhere** [comment]
请通过应用商店安装应用

**Comment by wherewhere** [comment]
已修复(如果你表达的和我猜的一样的话

**Comment by ZhouJze** [comment]
因win10屏蔽更新工具导致应用商店无法正常打开，用安装包安装会出现卡启动页，打开win10自动更新，已解决。
