### ISSUE TITLE
浏览图片时的界面异常

### ISSUE THREAD

**Issue by Mrquan998** [Coolapk-UWP/Coolapk-Lite#49]
### Describe the bug

酷安lite：23.1005.3289

### Steps to reproduce the bug

1.使用多窗口选项：开
以新窗口打开动态内的图片并关闭新窗口后，偶现主窗口自动最小化到任务栏并无法重新呼出，或者呼出后只显示白屏+酷安logo，只能关闭整个程序（程序可以在任务栏使用右键正常关闭，无需调用任务管理器）。

2.使用多窗口选项：关
浏览【圈子】分栏时，滚动页面后打开其中一条动态的图片，从图片查看器页返回到分栏页时，偶现分栏页自动重载并自动回滚到当前页的第一条动态处。

### App version

0.0.2

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### Device

Desktop

**Comment by wherewhere** [comment]
在测试页面将使用AppWindow选项关掉就行了
