### ISSUE TITLE
跟代理冲突

### ISSUE THREAD

**Issue by ae86ssl** [Coolapk-UWP/Coolapk-Lite#51]
### Describe the bug

开clash 就没网  代理或直连都没网  设置规则走直连也没用,关掉代理就好了

### Steps to reproduce the bug

11111111111111

### Screenshots

![111111111](https://github.com/Coolapk-UWP/Coolapk-Lite/assets/93923835/b69b94e4-d419-4ec5-b890-831ce621eda3)

### App version

0.0.2

### Windows version

Windows 10 version 1909 (18363, November 2019 Update)

### Device

Desktop

### Additional context

微软商店下载安装0.0.2版本

**Comment by wherewhere** [comment]
这不是一个bug，自己搜解除回环

**Comment by ae86ssl** [comment]
啊  你太棒了 是这样的 解决了 谢谢
