### ISSUE TITLE
现在正确的版本号能看评论，无法发送评论

### ISSUE THREAD

**Issue by momomobinx** [Coolapk-UWP/Coolapk-Lite#55]
### Describe the bug

酷安又增加了限制

### Steps to reproduce the bug

点击评论，发送评论

### Screenshots

![image](https://github.com/Coolapk-UWP/Coolapk-Lite/assets/21970770/7511c9dc-2039-4d82-a331-9875bc90a492)

### App version

0.0.2

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### Device

Desktop

**Comment by wherewhere** [comment]
建议来群里讨论 https://t.me/CoolapkUWP
