### ISSUE TITLE
在双击看大图后关闭大图窗口，有概率直接最小化主窗口

### ISSUE THREAD

**Issue by Michael-info** [Coolapk-UWP/Coolapk-Lite#63]
### Describe the bug

在双击看大图后关闭大图窗口，有概率直接最小化主窗口
此时点击任务栏和timeline无法打开窗口，但是把鼠标移动上去可以看到缩略图
![image](https://github.com/Coolapk-UWP/Coolapk-Lite/assets/72913045/1aa10384-3efc-43ca-86a7-5333c1b406de)

通过点击缩略图可以打开，此时有概率能打开主界面，但是缺失左上角返回使得不可用，还有双重标题栏现象
![image](https://github.com/Coolapk-UWP/Coolapk-Lite/assets/72913045/a0117283-e316-47df-b123-016b496ba24f)
此时完全不可以打开任何大图

### Steps to reproduce the bug

在双击看大图后关闭大图窗口，有概率直接最小化主窗口
此时点击任务栏和timeline无法打开窗口，但是把鼠标移动上去可以看到缩略图
通过点击缩略图可以打开，此时有概率能打开主界面，但是缺失左上角返回使得不可用

### Screenshots

![image](https://github.com/Coolapk-UWP/Coolapk-Lite/assets/72913045/84eec00e-cfc5-48fd-ba3a-58f9705c9137)
![image](https://github.com/Coolapk-UWP/Coolapk-Lite/assets/72913045/544cf92b-199a-4886-ac16-e005ef290041)

### App version

0.0.2

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### Device

Desktop

**Comment by wherewhere** [comment]
进入设置，测试页面，找到使用 AppWindow 选项，关掉

**Comment by wherewhere** [comment]
你用的是古董，自然没有了

**Comment by wherewhere** [comment]
Release不了了，酷安把新版本的API给锁了，直接使用已经无法正常使用了，所以就不发布了。。。
