### ISSUE TITLE
图片无法加载

### ISSUE THREAD

**Issue by youlan2333** [Coolapk-UWP/Coolapk-Lite#67]
### Describe the bug

![image](https://github.com/user-attachments/assets/a8a6e8a2-9118-4796-aa22-e8c7a1b228f7)
如图所示

### Steps to reproduce the bug

如图所示

### App version

0.0.3

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### Device

Desktop

**Comment by Geilberton** [comment]
遇到了同样的情况，
版本是：Windows 10 企业版 LTSC 21H2 19044.4529

**Comment by benqi88** [comment]
遇到了同样的问题

Windows 11 家庭中文版23H2

**Comment by DestrainJurY** [comment]
我这也加载不出来

**Comment by benqi88** [comment]
[Uploading Log - 20240915.log…]()

**Comment by benqi88** [comment]
[Log - 20240915.log](https://github.com/user-attachments/files/17006302/Log.-.20240915.log)

**Comment by GD2021** [comment]
我也是
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎8/‎28
操作系统版本	22631.4169
体验	Windows Feature Experience Pack 1000.22700.1034.0

**Comment by wherewhere** [comment]
用每日编译版
https://dev.azure.com/wherewhere/Coolapk-UWP/_build/latest?definitionId=5&branchName=master

**Comment by Geilberton** [comment]
> 用每日编译版 https://dev.azure.com/wherewhere/Coolapk-UWP/_build/latest?definitionId=5&branchName=master

it works. much appreciate

**Comment by GD2021** [comment]
> 用每日编译版 https://dev.azure.com/wherewhere/Coolapk-UWP/_build/latest?definitionId=5&branchName=master

每日编译版如何下载？

**Comment by wherewhere** [comment]
【【UWP】手把手教你下载自动编译安装包-哔哩哔哩】 https://b23.tv/7C2ME6X

**Comment by youlan2333** [comment]
> 用每日编译版 https://dev.azure.com/wherewhere/Coolapk-UWP/_build/latest?definitionId=5&branchName=master

已解决❤

**Comment by hange33** [comment]
只有lite版本正常啊
