### ISSUE TITLE
v24.914.4016 点击图片无法进入

### ISSUE THREAD

**Issue by ehehe066** [Coolapk-UWP/Coolapk-Lite#68]
### Describe the bug

  只有图片是宽图或者是长图的时候点击右下方的小图标能正常看图，是在更新 [修复打开图片会打开两次的问题](https://github.com/Coolapk-UWP/Coolapk-Lite/commit/0652128847c4e0bd38fac97c864b11d80e0cbc6a)这个提交之后出现的

### Steps to reproduce the bug

![image](https://github.com/user-attachments/assets/e662eb38-8c22-4426-b33b-ad254b6a25c3)

### App version

0.0.3

### Windows version

Windows 10 version 1809 (17763, October 2018 Update)

### Device

Desktop

**Comment by wherewhere** [comment]
好气

**Comment by wherewhere** [comment]
提交了
