### ISSUE TITLE
图片无法加载

### ISSUE THREAD

**Issue by FutureSJTU** [Coolapk-UWP/Coolapk-Lite#70]
### Describe the bug

图片无法加载
日志报错是无法连接服务器

### Steps to reproduce the bug

![image](https://github.com/user-attachments/assets/f733ef17-b3d4-463f-a839-997c509ebc63)

### Expected behavior

日志如下：

4|2024-10-15T17:12:34.5095157+00:00|ERROR|23|NetworkHelper|
Message: net_http_client_execution_error
HResult: -2147012867 (0x80072EFD)
   at CoolapkLite!<BaseAddress>+0x120d31c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xbd9e84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xb2472b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xc0b3b4
 --> System.Net.Http.HttpRequestException: net_http_client_execution_error ---> System.Exception: 无法找到与此错误代码关联的文本。

无法与服务器建立连接

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0x120dc69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0x120d25f
   Exception_EndOfInnerExceptionStack
   at CoolapkLite!<BaseAddress>+0x120d31c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xbd9e84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xb2472b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xc0b3b4
2|2024-10-15T17:17:06.7649969+00:00|ERROR|32|NetworkHelper|
Message: net_http_client_execution_error
HResult: -2147012867 (0x80072EFD)
   at CoolapkLite!<BaseAddress>+0x120d31c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xbd9e84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xb2472b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xc0b3b4
 --> System.Net.Http.HttpRequestException: net_http_client_execution_error ---> System.Exception: 无法找到与此错误代码关联的文本。

无法与服务器建立连接

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0x120dc69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0x120d25f
   Exception_EndOfInnerExceptionStack
   at CoolapkLite!<BaseAddress>+0x120d31c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xbd9e84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xb2472b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xc0b3b4
3|2024-10-15T17:17:16.7074056+00:00|ERROR|32|NetworkHelper|
Message: net_http_client_execution_error
HResult: -2147012867 (0x80072EFD)
   at CoolapkLite!<BaseAddress>+0x120d31c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xbd9e84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xb2472b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xc0b3b4
 --> System.Net.Http.HttpRequestException: net_http_client_execution_error ---> System.Exception: 无法找到与此错误代码关联的文本。

无法与服务器建立连接

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0x120dc69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0x120d25f
   Exception_EndOfInnerExceptionStack
   at CoolapkLite!<BaseAddress>+0x120d31c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xbd9e84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xb2472b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xc0b3b4
4|2024-10-15T17:21:05.2782207+00:00|ERROR|4|NetworkHelper|
Message: net_http_client_execution_error
HResult: -2147012867 (0x80072EFD)
   at CoolapkLite!<BaseAddress>+0x120d31c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xbd9e84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xb2472b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xc0b3b4
 --> System.Net.Http.HttpRequestException: net_http_client_execution_error ---> System.Exception: 无法找到与此错误代码关联的文本。

无法与服务器建立连接

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0x120dc69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0x120d25f
   Exception_EndOfInnerExceptionStack
   at CoolapkLite!<BaseAddress>+0x120d31c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xbd9e84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xb2472b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xc0b3b4
5|2024-10-15T17:22:05.3398692+00:00|ERROR|23|NetworkHelper|
Message: net_http_client_execution_error
HResult: -2147012867 (0x80072EFD)
   at CoolapkLite!<BaseAddress>+0x120d31c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xbd9e84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xb2472b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xc0b3b4
 --> System.Net.Http.HttpRequestException: net_http_client_execution_error ---> System.Exception: 无法找到与此错误代码关联的文本。

无法与服务器建立连接

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0x120dc69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0x120d25f
   Exception_EndOfInnerExceptionStack
   at CoolapkLite!<BaseAddress>+0x120d31c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xbd9e84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xb2472b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xc0b3b4
6|2024-10-15T17:23:06.4354033+00:00|ERROR|62|NetworkHelper|
Message: net_http_client_execution_error
HResult: -2147012867 (0x80072EFD)
   at CoolapkLite!<BaseAddress>+0x120d31c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xbd9e84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xb2472b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xc0b3b4
 --> System.Net.Http.HttpRequestException: net_http_client_execution_error ---> System.Exception: 无法找到与此错误代码关联的文本。

无法与服务器建立连接

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0x120dc69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0x120d25f
   Exception_EndOfInnerExceptionStack
   at CoolapkLite!<BaseAddress>+0x120d31c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xbd9e84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xb2472b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x4d5c60
   at SharedLibrary!<BaseAddress>+0x4d5be8
   at SharedLibrary!<BaseAddress>+0x4d5ba7
   at CoolapkLite!<BaseAddress>+0xc0b3b4

### App version

0.0.3

### Windows version

Insider Build (xxxxx)

### Device

Desktop

**Comment by wherewhere** [comment]
#67

**Comment by FutureSJTU** [comment]
> #67
明白了，感谢
