### ISSUE TITLE
酷安lite自动退出没有提示

### ISSUE THREAD

**Issue by jh13champion** [Coolapk-UWP/Coolapk-Lite#73]
### Describe the bug

使用系统为win11 23h2
应用版本为酷安lite 24.1106.4118
酷安lite不在前台焦点后5分钟左右就自动退出没有提示

### Steps to reproduce the bug

1.打开酷安lite
2.切换到其他前台，使酷安lite不在焦点
3.等待5分钟左右自动退出

### App version

0.0.3

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### Device

Desktop

**Comment by wherewhere** [comment]
前往设置>测试页面关闭后台任务，猜测是后台任务写坏了

**Comment by wherewhere** [comment]
别关啊，这不还没修好麼
